"""reivew_score -> score

Revision ID: 0b956cc41533
Revises: 96659c83c72f
Create Date: 2023-02-09 12:58:25.058182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b956cc41533'
down_revision = '96659c83c72f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('score', sa.Integer(), nullable=True))
    op.drop_column('reviews', 'review_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_score', sa.INTEGER(), nullable=True))
    op.drop_column('reviews', 'score')
    # ### end Alembic commands ###
