"""reivew_score attr

Revision ID: 96659c83c72f
Revises: 2c8c9fade8fd
Create Date: 2023-02-09 12:56:19.567000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96659c83c72f'
down_revision = '2c8c9fade8fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_score', sa.Integer(), nullable=True))
    op.drop_column('reviews', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('score', sa.INTEGER(), nullable=True))
    op.drop_column('reviews', 'review_score')
    # ### end Alembic commands ###
